### ISSUE TITLE
Can I use in a menuItem?

### ISSUE THREAD

**Issue by fabioebner** [mcollovati/enhanced-window-opener#2]
I trying without success to use this with a menuItem.

It`s possible? how? 

tks

**Comment by mcollovati** [comment]
MenuItem is currently not supported: I'll try to find a way to make it work.

**Comment by mcollovati** [comment]
Closing this as an issue has been opened for this feature request

**Comment by mcollovati** [comment]
Version 0.3 with support for MenuBar extension is available on directory; by now only Vaadin 8.x is supported.

Feedback is welcome; feel free to open other issues.
Let me know if you need a Vaadin 7 backport
