### ISSUE TITLE
Use a custom button

### ISSUE THREAD

**Issue by fabioebner** [mcollovati/enhanced-window-opener#6]
Can I use a custom button? I wanna to use one button to download a file so I need to create my button, extend he in BrowserWindowOpener, so I want to pass this button to r comp. It's possible?

tks

**Comment by mcollovati** [comment]
There should be no problem on extending a custom button. 
If you have issues doing this please post some code; maybe I've not understand the problem

**Comment by mcollovati** [comment]
@fabioebner is the issue still valid? or may I close it?

**Comment by fabioebner** [comment]
I have not tried yet, I believe I will have to use a custom component in the body of the popup, I wanted to use one of the buttons, such as YES to open the window

**Comment by mcollovati** [comment]
Closing due to lack of feedback. 
Feel free to add comments if the issue is still valid
